version: "3"
services:
  pgsql:
    image: "postgres:9.6-alpine"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "statink2"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "statink2testfire"
      POSTGRES_INITDB_ARGS: "--data-checksums --locale=en_US.UTF8 --encoding=UTF-8"
    networks:
      - "internal"

  webapp:
    build:
      context: "./webapp"
      args:
        GITHUB_TOKEN: "%GITHUB_TOKEN%"
        GIT_REVISION: "%GIT_REVISION%"
    volumes:
      - "applog:/var/www/site/runtime/logs"
      - "appassets:/var/www/site/web/assets"
      - "images:/var/www/site/web/images"
      - "profile-images:/var/www/site/web/profile-images"
      - "/mnt/storage1/testfire2-uploads:/var/www/site/runtime/image-archive"
    links:
      - "pgsql"
    networks:
      - "internal"

  httpd:
    build:
      context: "./docker/h2o"
    volumes:
      - "appassets:/var/www/site/web/assets:ro"
      - "images:/var/www/site/web/images:ro"
      - "profile-images:/var/www/site/web/profile-images:ro"
    links:
      - "webapp"
    networks:
      - "internal"
      - "expose"

volumes:
  pgdata:
  appassets:
  applog:
  images:
  profile-images:
  image-archive:

networks:
  internal:
  expose:
    external: true
